#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
 	echo "Not running as root"
	exit
fi

arecord=""
CNAMErecord=""
aip=""
dom=""

#CNAME
if [[ $1 = "-t" ]] && [[ $2 = CNAME ]]; then
 	echo "Creating CNAME record"
 	CNAMErecord=$3
	dom=$4
	#get wanted alias
	IFS='.' read var1 var2 <<< "$dom"
	AliasTo="$var1" 
 	Domain="$var2"
	
	DbFile=/etc/bind/db.$Domain
 	echo "$CNAMErecord"'     IN         CNAME        '"$AliasTo" >> $DbFile

	#adjust serialnr
 	Serial=$(grep 'Serial' $DbFile)
 	SerialNumber=$(echo $Serial | sed 's/[^0-9]*//g')
	((SerialNumber++))
	newSerial='                             '"$SerialNumber"'        ;Serial'
 	sed -i "s/.*Serial.*/\t\t $newSerial/g" $DbFile

#MX record
elif [[ $1 = "-t" ]] && [[ $2 = MX ]]; then
 	echo "Creating MX record"
 	arecord=$3
 	aip=$4
	dom=$5
 	echo "$dom"
	DBfile=/etc/bind/db.$dom
	echo '@     IN     MX    10 '"$arecord"'.'"$dom"'.' >> $DBfile
	echo "$arecord"'     IN     A       '"$aip" >> $DBfile

	#adjust serialnr
	Serial=$(grep 'Serial' $DBfile)
	SerialNumber=$(echo $Serial| sed 's/[^0-9]*//g')
	((SerialNumber++))
	newSerial='                            '"$SerialNumber"'        ;Serial'
	sed -i "s/.*Serial.*/\t\t $newSerial/g" $DBfile

#A record
elif [[ $1 = "-t" ]] && [[ $2 = A ]] || [[ $1 != "-t" ]]; then
	if [[ $1 = "-t" ]]; then
 		arecord=$3
 		aip=$4
		dom=$5
	else
 		arecord=$1
		aip=$2
 		dom=$3
	fi
	echo 'Creating '"$arecord"'-record for ip: '"$aip"' & domain: '"$dom"

	DBFILE=/etc/bind/db.$dom
	echo 'file = '"$DBFILE"
	echo "$arecord"'    IN        A        '"$aip" >> $DBFILE

 	#adjust serialnr
 	Serial=$(grep 'Serial' $DBFILE)
 	SerialNumber=$(echo $Serial | sed 's/[^0-9]*//g')
 	((SerialNumber++))
	newSerial='                              '"$SerialNumber"'         ;Serial'
 	sed -i "s/.*Serial.*/\t\t $newSerial/g" $DBFILE

fi

#Restart bind9 service
echo 'Restarting bind9'
systemctl restart bind9

echo 'Finished'
